<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProjectCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                'category_name' => 'Education and Non-Formal Education (NFE)',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Education and Non-Formal Education (NFE)'))),
                'category_description' => '<p><strong>Image:</strong> Students learning in an outdoor classroom setting</p><p><strong>Situation:</strong> Low literacy rates and limited access to formal education in many communities</p><p><strong>Task:</strong> Improve literacy and educational engagement among children and community members</p><p><strong>Action:</strong> Implemented education programs, including NFE initiatives, prioritizing education and facilitating children\'s transition to formal education</p><p><strong>Result:</strong> Enrolled 1,200 children in NFE programs; 800 transitioned to formal education, increasing community literacy rates by 15%</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Rehabilitation Program',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Rehabilitation Program'))),
                'category_description' => '<p><strong>Image:</strong> A family standing in front of their newly built home</p><p><strong>Situation:</strong> High need for rehabilitation to ensure sustainable development in the community</p><p><strong>Task:</strong> Rehabilitate the needy by providing resources for self-reliance</p><p><strong>Action:</strong> Utilized zakat funds and donations to provide vehicles, cattle, small startup capital, and built homes for those displaced by natural disasters</p><p><strong>Result:</strong> Rehabilitated 500 families, reducing their poverty levels by 40% and achieving self-reliance for 80% of beneficiaries</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Health and Hygiene Programme',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Health and Hygiene Programme'))),
                'category_description' => '<p><strong>Image:</strong> A community health worker demonstrating hand washing techniques</p><p><strong>Situation:</strong> Limited awareness and poor practices related to health and hygiene in the community</p><p><strong>Task:</strong> Enhance health and hygiene awareness among community members</p><p><strong>Action:</strong> Conducted weekly group meetings to educate community members on health and hygiene practices</p><p><strong>Result:</strong> 95% of 2,500 community members regularly attended, leading to a 30% improvement in hygiene practices and a 20% reduction in preventable diseases</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'EID Food Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'EID Food Distribution'))),
                'category_description' => '<p><strong>Image:</strong> A man handing a bowl of food to a woman kneeling on cracked earth, with others holding bowls</p><p><strong>Situation:</strong> Food insecurity among economically disadvantaged city residents during Eid and Ramadan</p><p><strong>Task:</strong> Provide essential food items to these residents</p><p><strong>Action:</strong> Distributed food packages containing rice, oil, onion, potato, sugar, flour, salt, lentil, milk powder, vermicelli, chickpea, puffed rice, and spices</p><p><strong>Result:</strong> Distributed 1,000 food packages, benefiting 5,000 individuals and improving their food security during the festive period</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Qurbani Meat Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Qurbani Meat Distribution'))),
                'category_description' => '<p><strong>Image:</strong> A green delivery truck labeled "MEAT" and two men carrying boxes of meat</p><p><strong>Situation:</strong> Many needy individuals could not afford meat during Eid-ul-Adha</p><p><strong>Task:</strong> Ensure these individuals could partake in the Eid-ul-Adha celebrations</p><p><strong>Action:</strong> Organized the distribution of Qurbani meat to destitute individuals, including refugees and ethnic communities</p><p><strong>Result:</strong> Distributed 3,000 kilograms of meat, benefiting 6,000 individuals and bringing joy and nutrition to families</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Fresh Fruits Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Fresh Fruits Distribution'))),
                'category_description' => '<p><strong>Image:</strong> A truck with people loading/unloading boxes marked with crosses (medical/health icons)</p><p><strong>Situation:</strong> Deprived communities lacked access to fresh, nutritious fruits</p><p><strong>Task:</strong> Improve the nutrition levels of these communities</p><p><strong>Action:</strong> Distributed seasonal fresh fruits like mangoes to children and women in underprivileged areas</p><p><strong>Result:</strong> Distributed 2,500 kilograms of mangoes, improving the nutrition of 1,200 children and women</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Book Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Book Distribution'))),
                'category_description' => '<p><strong>Image:</strong> Students receiving new academic books in a library</p><p><strong>Situation:</strong> Institutions in remote areas lacked essential academic and research books</p><p><strong>Task:</strong> Provide these resources to support education and research</p><p><strong>Action:</strong> Distributed useful literature, academic, and research books to research centers, libraries, and institutions</p><p><strong>Result:</strong> Distributed 5,000 books to 20 institutions, benefiting over 3,000 students and researchers</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Instituting Vocational Training Center',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Instituting Vocational Training Center'))),
                'category_description' => '<p><strong>Image:</strong> Individuals learning to use sewing machines in a training center</p><p><strong>Situation:</strong> High poverty rates and limited job opportunities in remote areas</p><p><strong>Task:</strong> Provide vocational training to improve job prospects</p><p><strong>Action:</strong> Established vocational training centers focusing on cottage industries and electrical work, providing training and equipment like Tool Boxes</p><p><strong>Result:</strong> Trained 300 individuals, with 70% securing jobs or starting their own businesses in the trained sectors</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Employment Program',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Employment Program'))),
                'category_description' => '<p><strong>Image:</strong> Small business owners standing proudly in front of their shops</p><p><strong>Situation:</strong> High unemployment rates, exacerbated by the post-pandemic economic environment</p><p><strong>Task:</strong> Create employment opportunities in rural areas where people prefer work over relief</p><p><strong>Action:</strong> Initiated Small and Medium Enterprise (SME) and Cooperative Management programs based on local demand</p><p><strong>Result:</strong> Created employment opportunities for 400 individuals, with 80% securing steady jobs or starting their own enterprises</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Laying Deep Water Wells',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Laying Deep Water Wells'))),
                'category_description' => '<p><strong>Image:</strong> Community members pumping clean water from a newly installed tube well</p><p><strong>Situation:</strong> Scarcity of safe drinking water in disaster-affected and southern regions</p><p><strong>Task:</strong> Provide access to safe, arsenic-free water</p><p><strong>Action:</strong> Installed deep tube wells in these areas, engaging local stakeholders for maintenance and management</p><p><strong>Result:</strong> Installed 50 tube wells, providing safe drinking water to 500 families, significantly improving their health</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Agriculture Project',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Agriculture Project'))),
                'category_description' => '<p><strong>Image:</strong> A farmer tending to crops in a newly seeded field</p><p><strong>Situation:</strong> Frequent natural calamities leading to loss of agricultural fields, crops, and cattle</p><p><strong>Task:</strong> Support farmers to recover and sustain their livelihoods</p><p><strong>Action:</strong> Distributed seeds for farming, cattle for cultivating, and provided cows and goats for animal husbandry</p><p><strong>Result:</strong> Assisted 600 farmers in regaining their livelihoods, reducing poverty levels by 35%</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Medical Aid for Poor',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Medical Aid for Poor'))),
                'category_description' => '<p><strong>Image:</strong> A doctor examining a patient in a rural clinic</p><p><strong>Situation:</strong> Poor and needy individuals unable to afford medical treatment for chronic diseases</p><p><strong>Task:</strong> Provide medical treatment support for these individuals</p><p><strong>Action:</strong> Covered medical costs and provided medicine support to those suffering from enduring diseases</p><p><strong>Result:</strong> Supported 150 individuals in receiving necessary medical treatment, improving their health outcomes</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Project Marriage',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Project Marriage'))),
                'category_description' => '<p><strong>Image:</strong> A couple smiling during a modest community wedding ceremony</p><p><strong>Situation:</strong> Many boys and girls from poor families unable to afford marriage expenses</p><p><strong>Task:</strong> Provide support for these individuals to get married with reasonable expenses</p><p><strong>Action:</strong> Funded marriage expenses for needy individuals, focusing on orphans and underprivileged backgrounds</p><p><strong>Result:</strong> Supported 100 marriages, bringing happiness and stability to families</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Winter Clothing Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Winter Clothing Distribution'))),
                'category_description' => '<p><strong>Image:</strong> Children wearing warm new coats and smiling</p><p><strong>Situation:</strong> Severe cold conditions in northern areas, with inadequate warmth clothing</p><p><strong>Task:</strong> Provide warmth clothing and blankets to those in need</p><p><strong>Action:</strong> Distributed thousands of blankets in districts like Panchagarh, Kurigram, and Dinajpur</p><p><strong>Result:</strong> Provided warmth and protection from the cold to 2,000 individuals during winter months</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Project Entrepreneurship',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Project Entrepreneurship'))),
                'category_description' => '<p><strong>Image:</strong> A young entrepreneur selling fresh produce at a market stall</p><p><strong>Situation:</strong> High competition and challenges in job markets, with many seeking entrepreneurial opportunities</p><p><strong>Task:</strong> Encourage and support entrepreneurship to create job opportunities</p><p><strong>Action:</strong> Provided aid for prospective sectors like agriculture, farming, and transportation</p><p><strong>Result:</strong> Supported 150 entrepreneurs, creating job opportunities for 500 individuals</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Education Scholarship',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Education Scholarship'))),
                'category_description' => '<p><strong>Image:</strong> A student holding a scholarship award certificate</p><p><strong>Situation:</strong> Talented students from poor families unable to continue their education</p><p><strong>Task:</strong> Provide scholarships to support these students</p><p><strong>Action:</strong> Offered scholarships to students, ensuring they could continue their studies</p><p><strong>Result:</strong> Supported 200 students, reducing dropout rates and fostering educational achievement</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Constructing Home for Homeless',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Constructing Home for Homeless'))),
                'category_description' => '<p><strong>Image:</strong> Construction workers building the walls of a new brick house</p><p><strong>Situation:</strong> Homelessness due to natural calamities and other vulnerabilities</p><p><strong>Task:</strong> Provide permanent shelter and rehabilitation</p><p><strong>Action:</strong> Built and repaired homes for homeless and rootless people, sometimes acquiring land for permanent shelters</p><p><strong>Result:</strong> Constructed 50 homes, providing secure housing for 200 individuals</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Rehabilitation Program After Natural Calamities',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Rehabilitation Program After Natural Calamities'))),
                'category_description' => '<p><strong>Image:</strong> Aid workers providing relief supplies and temporary shelter materials</p><p><strong>Situation:</strong> Frequent natural disasters leading to loss of land, homes, and livelihoods</p><p><strong>Task:</strong> Provide rehabilitation and support to affected individuals</p><p><strong>Action:</strong> Arranged shelter, managed job opportunities, and provided educational sponsorships</p><p><strong>Result:</strong> Rehabilitated 300 individuals, restoring their livelihoods and ensuring their dignity</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Constructing Sanitary Latrine',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Constructing Sanitary Latrine'))),
                'category_description' => '<p><strong>Image:</strong> A newly constructed hygienic concrete latrine in a village</p><p><strong>Situation:</strong> Lack of safe and healthy latrines in certain areas</p><p><strong>Task:</strong> Provide safe and sanitary latrines</p><p><strong>Action:</strong> Built healthy toilets in remote and disaster-affected areas, including refugee camps</p><p><strong>Result:</strong> Constructed 100 sanitary latrines, benefiting 400 families and reducing hygiene-related diseases</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Eye Cataracts Operation Project',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Eye Cataracts Operation Project'))),
                'category_description' => '<p><strong>Image:</strong> An elderly patient having their eyes checked by an ophthalmologist</p><p><strong>Situation:</strong> Many individuals suffering from eye cataracts unable to afford treatment</p><p><strong>Task:</strong> Provide free eye cataracts operations and treatment</p><p><strong>Action:</strong> Organized health camps with certified doctors, offering free treatment and medicine</p><p><strong>Result:</strong> Conducted 200 cataracts operations, restoring vision for 200 individuals</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Circumcision Project',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Circumcision Project'))),
                'category_description' => '<p><strong>Image:</strong> A medical professional performing a safe procedure in a sterile room</p><p><strong>Situation:</strong> Families in rural areas unable to afford circumcision operations for their children</p><p><strong>Task:</strong> Provide safe and hygienic circumcision procedures</p><p><strong>Action:</strong> Supported circumcision operations, ensuring health consciousness and adherence to Islamic rituals</p><p><strong>Result:</strong> Conducted 150 circumcision operations, improving health outcomes</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Free Health Camp',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Free Health Camp'))),
                'category_description' => '<p><strong>Image:</strong> Patients lined up outside a tent waiting for medical consultations</p><p><strong>Situation:</strong> General lack of health consciousness and access to healthcare in poverty-stricken areas</p><p><strong>Task:</strong> Provide free healthcare services</p><p><strong>Action:</strong> Organized health camps with qualified doctors, offering free treatment, prescriptions, and medicine</p><p><strong>Result:</strong> Provided healthcare services to 1,000 individuals in refugee camps, flood-affected areas, and remote regions</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'APKS Craft & Training Center for Third Gender & Bohemian',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'APKS Craft & Training Center for Third Gender & Bohemian'))),
                'category_description' => '<p><strong>Image:</strong> Artisans working on colorful textiles and crafts in a workshop</p><p><strong>Situation:</strong> Third-gender individuals and bohemians face social exclusion and lack of employment opportunities</p><p><strong>Task:</strong> Establish a training center and cottage factory to provide vocational training and employment</p><p><strong>Action:</strong> Initiated a boutique with dyeing sections run by third-gender individuals, producing items for sale via e-commerce and physical outlets</p><p><strong>Result:</strong> Trained and employed 50 individuals, creating a platform for economic independence</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Old Age Allowance',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Old Age Allowance'))),
                'category_description' => '<p><strong>Image:</strong> An elderly woman smiling while receiving her monthly allowance envelope</p><p><strong>Situation:</strong> Elderly individuals facing loneliness and financial difficulties</p><p><strong>Task:</strong> Provide regular allowances to senior citizens</p><p><strong>Action:</strong> Distributed allowances to senior citizens, ensuring regular financial support</p><p><strong>Result:</strong> Supported 200 senior citizens, improving their quality of life and reducing financial stress</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Electric House Wiring Training',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Electric House Wiring Training'))),
                'category_description' => '<p><strong>Image:</strong> Youth practicing installing electrical wires on a training board</p><p><strong>Situation:</strong> High unemployment among youth in remote areas</p><p><strong>Task:</strong> Provide training in electric house wiring</p><p><strong>Action:</strong> Conducted training sessions and provided essential tools and equipment</p><p><strong>Result:</strong> Trained 100 youth, enabling them to start their own businesses or find employment</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Computer Training Center',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Computer Training Center'))),
                'category_description' => '<p><strong>Image:</strong> Students typing on computers in a modern digital classroom</p><p><strong>Situation:</strong> Lack of computer skills among youth</p><p><strong>Task:</strong> Provide comprehensive computer training</p><p><strong>Action:</strong> Offered courses in basic computer skills, graphic design, web development, and software development, alongside stipends</p><p><strong>Result:</strong> Trained 150 students, enhancing their employability in the digital economy</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Blood Donation and Blood Component Support',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Blood Donation and Blood Component Support'))),
                'category_description' => '<p><strong>Image:</strong> A volunteer donating blood while a nurse monitors the process</p><p><strong>Situation:</strong> Need for blood donations for medical emergencies</p><p><strong>Task:</strong> Organize blood donation campaigns and build a robust donor network</p><p><strong>Action:</strong> Conducted blood donation drives and grouping campaigns</p><p><strong>Result:</strong> Collected 500 units of blood, supporting medical emergencies and saving lives</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Creating Awareness on Road Safety',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Creating Awareness on Road Safety'))),
                'category_description' => '<p><strong>Image:</strong> A crossing guard holding a "STOP" sign for children crossing the road</p><p><strong>Situation:</strong> High incidence of road accidents causing fatalities and injuries</p><p><strong>Task:</strong> Promote road safety awareness and training</p><p><strong>Action:</strong> Conducted awareness campaigns and driver training sessions</p><p><strong>Result:</strong> Reached 10,000 individuals, promoting safer driving practices and reducing accident rates</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Rapid Response for Flood-Affected People',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Rapid Response for Flood-Affected People'))),
                'category_description' => '<p><strong>Image:</strong> Rescuers distributing essential supplies from a boat in a flooded area</p><p><strong>Situation:</strong> Floods causing widespread damage and displacement</p><p><strong>Task:</strong> Provide immediate and post-disaster relief</p><p><strong>Action:</strong> Distributed food, medicine, and shelter materials, and supported post-disaster rehabilitation</p><p><strong>Result:</strong> Assisted 1,000 flood-affected individuals in recovery and rebuilding efforts</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Iftar Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Iftar Distribution'))),
                'category_description' => '<p><strong>Image:</strong> Two Muslim men smiling, one offering a bowl of dates under a "Ramadan Kareem" sign and decorative lanterns</p><p><strong>Situation:</strong> Vulnerable communities unable to afford Iftar during Ramadan</p><p><strong>Task:</strong> Provide Iftar packages to those in need</p><p><strong>Action:</strong> Distributed food packages containing rice, chickpeas, dates, and other essentials</p><p><strong>Result:</strong> Provided Iftar packages to 1,000 families, ensuring they could observe Ramadan with dignity</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Eid Gift Distribution',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Eid Gift Distribution'))),
                'category_description' => '<p><strong>Image:</strong> A man handing a bowl of food to a woman kneeling on the ground</p><p><strong>Situation:</strong> Financially challenged individuals unable to celebrate Eid</p><p><strong>Task:</strong> Distribute Eid gifts to needy individuals</p><p><strong>Action:</strong> Provided Eid packages to community members, including rickshaw pullers, drivers, and teachers</p><p><strong>Result:</strong> Distributed 500 Eid packages, bringing joy to underprivileged families</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Cooked Food Distribution During Lockdown',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Cooked Food Distribution During Lockdown'))),
                'category_description' => '<p><strong>Image:</strong> Volunteers handing out hot meal boxes to workers on the street</p><p><strong>Situation:</strong> Food insecurity among vulnerable populations during lockdowns</p><p><strong>Task:</strong> Distribute cooked food to those in need</p><p><strong>Action:</strong> Provided cooked meals to working individuals and street children</p><p><strong>Result:</strong> Distributed 1,000 meals, alleviating hunger during the lockdown</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Telemedicine Service',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Telemedicine Service'))),
                'category_description' => '<p><strong>Image:</strong> A doctor with a clipboard appearing on a laptop screen next to a heart monitor icon</p><p><strong>Situation:</strong> Limited access to healthcare during the COVID-19 pandemic</p><p><strong>Task:</strong> Provide telemedicine services to the community</p><p><strong>Action:</strong> Established a telemedicine network with volunteer doctors via phone and video calls</p><p><strong>Result:</strong> Provided medical consultations to 2,000 individuals</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Relief Distribution During Lockdown',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Relief Distribution During Lockdown'))),
                'category_description' => '<p><strong>Image:</strong> A man sitting on the ground receiving cash from another man under a crescent moon and stars</p><p><strong>Situation:</strong> Lockdowns create economic hardships</p><p><strong>Task:</strong> Provide relief packages to ensure families have essentials to survive</p><p><strong>Action:</strong> Distributed essential relief packages and food</p><p><strong>Result:</strong> Ensured families had the necessary supplies to survive the lockdown period</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Cash Distribution During COVID-19',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Cash Distribution During COVID-19'))),
                'category_description' => '<p><strong>Image:</strong> A family receiving a cash transfer envelope from an aid worker</p><p><strong>Situation:</strong> Economic difficulties faced by families during the COVID-19 pandemic</p><p><strong>Task:</strong> Provide cash assistance to those in need</p><p><strong>Action:</strong> Distributed cash to families to help with urgent expenses such as food and medicine</p><p><strong>Result:</strong> Assisted 300 families with cash support</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Response on COVID-19',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Response on COVID-19'))),
                'category_description' => '<p><strong>Image:</strong> Medical staff wearing PPE and distributing hygiene kits</p><p><strong>Situation:</strong> Global COVID-19 pandemic causing health and economic crises</p><p><strong>Task:</strong> Provide multi-faceted support to affected communities</p><p><strong>Action:</strong> Distributed face masks, hand sanitizers, food packages, and provided telemedicine services</p><p><strong>Result:</strong> Supported 5,000 individuals through various initiatives</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Projects Sadqah Zaria',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Projects Sadqah Zaria'))),
                'category_description' => '<p><strong>Image:</strong> A community gathering near a newly established Madrasah building</p><p><strong>Situation:</strong> Lack of essential Islamic infrastructure and educational facilities in remote and underprivileged areas</p><p><strong>Task:</strong> Implement projects that contribute to community development and Islamic education</p><p><strong>Action:</strong> Initiated mosque construction, Madrasah establishment, student sponsorship, Wudhukhana building, and Sunnah wedding support</p><p><strong>Result:</strong> Benefited communities by providing essential infrastructure, education, and spiritual guidance</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'The Mosque Project',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'The Mosque Project'))),
                'category_description' => '<p><strong>Image:</strong> A beautiful newly built mosque with a community praying inside</p><p><strong>Situation:</strong> Communities lacking proper mosque facilities, forcing residents to travel long distances</p><p><strong>Task:</strong> Construct mosques in remote areas and refugee camps</p><p><strong>Action:</strong> Collaborated with stakeholders, obtained Waqf land, and constructed facilities</p><p><strong>Result:</strong> Completed mosque constructions in Punchagarh, Kurigram, and Cox’s Bazaar Rohingya Camp</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Madrasah for All',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Madrasah for All'))),
                'category_description' => '<p><strong>Image:</strong> Children reading the Quran together in a Madrasah classroom</p><p><strong>Situation:</strong> Lack of Islamic education facilities leading to societal ignorance in remote communities</p><p><strong>Task:</strong> Establish Madrasahs and ensure operational sustainability</p><p><strong>Action:</strong> Established Madrasahs, provided educational materials, and supported teachers’ salaries</p><p><strong>Result:</strong> Enabled access to Islamic education for hundreds of students</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Student Sponsorship',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Student Sponsorship'))),
                'category_description' => '<p><strong>Image:</strong> A sponsored student happily holding their new school supplies and uniform</p><p><strong>Situation:</strong> Financial constraints hindering students’ access to education</p><p><strong>Task:</strong> Provide sponsorship for tuition fees, nutrition, health, stationery, and uniforms</p><p><strong>Action:</strong> Sponsored students in Madrasahs and schools</p><p><strong>Result:</strong> Supported talented students, enabling them to focus on academic excellence</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Building Wudhukhana',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Building Wudhukhana'))),
                'category_description' => '<p><strong>Image:</strong> Worshippers performing ablution at a new clean Wudhukhana facility</p><p><strong>Situation:</strong> Lack of proper Wudhukhana facilities in mosque-prayer rooms</p><p><strong>Task:</strong> Build Wudhukhana facilities with deep tube wells</p><p><strong>Action:</strong> Built Wudhukhana facilities ensuring access to clean water for ablution</p><p><strong>Result:</strong> Facilitated proper purification rituals for worshippers, promoting hygiene</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Madrasah Sponsorship',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Madrasah Sponsorship'))),
                'category_description' => '<p><strong>Image:</strong> A Madrasah building with an active class ongoing</p><p><strong>Situation:</strong> Madrasahs struggling with financial crises and operational challenges</p><p><strong>Task:</strong> Sponsor Madrasahs to mitigate financial strains</p><p><strong>Action:</strong> Provided financial support and monitored operations</p><p><strong>Result:</strong> Sustained Madrasah operations during crises, preserving educational opportunities</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Project Sunnah Wedding',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Project Sunnah Wedding'))),
                'category_description' => '<p><strong>Image:</strong> A couple dressed modestly taking their vows in a Sunnah wedding ceremony</p><p><strong>Situation:</strong> Societal pressures leading to extravagant weddings and financial burdens</p><p><strong>Task:</strong> Support youth opting for Sunnah weddings</p><p><strong>Action:</strong> Provided guidance and support for Sunnah weddings, emphasizing simplicity</p><p><strong>Result:</strong> Encouraged adherence to Sunnah practices, promoting modesty</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Founding Quranic Maktab',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Founding Quranic Maktab'))),
                'category_description' => '<p><strong>Image:</strong> Young children learning the Arabic alphabet in a Maktab</p><p><strong>Situation:</strong> Lack of Quranic Maktab schools in remote areas</p><p><strong>Task:</strong> Found Quranic Maktab schools in remote areas</p><p><strong>Action:</strong> Established schools with morning and afternoon shifts and provided educational materials</p><p><strong>Result:</strong> Enabled children to receive fundamental Islamic education</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_name' => 'Organizing Imam & Teachers Training',
                'category_slug' => trim(strtolower(str_replace([' ', '&', '(', ')', ','], ['-', 'and', '', '', ''], 'Organizing Imam & Teachers Training'))),
                'category_description' => '<p><strong>Image:</strong> Imams and teachers listening attentively to a scholar during a training workshop</p><p><strong>Situation:</strong> Limited access to training for Imams and teachers in remote regions</p><p><strong>Task:</strong> Organize training sessions for Imams and teachers</p><p><strong>Action:</strong> Conducted training programs with qualified trainers and scholars</p><p><strong>Result:</strong> Enhanced skills of Imams and teachers to better serve their communities</p>',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Since we are generating the slugs using str_replace, let's just make sure there are no duplicate dashes
        foreach ($categories as &$category) {
            $category['category_slug'] = preg_replace('/-+/', '-', $category['category_slug']);
        }

        DB::table('project_categories')->insert($categories);
    }
}
